services:
  - type: pserv
    name: openapi
    plan: free
    region: oregon
    databaseName: openapi_db
    user: openapi_user
  - type: web
    name: product-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: DB_NAME
        value: openapi_db
      - key: DB_USER
        value: openapi_user
      - key: DB_PASSWORD
        value: ujacrRI7ZWEdKrNvPsU6izyhtvhyrcLP
      - key: DB_HOST
        value: dpg-d5git1q4d50c73b0s2f0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
    healthCheckPath: /api/products/